# Generated by Django 2.2.3 on 2019-10-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20191017_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='index',
            field=models.IntegerField(default=-1),
        ),
    ]
