# Generated by Django 2.2.3 on 2019-10-18 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_auto_20191018_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='ind',
            new_name='todo_id',
        ),
    ]
